# Generated by Django 5.1.2 on 2024-11-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_train_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='arrival_time',
            new_name='return_time',
        ),
    ]
