# Generated by Django 5.1.2 on 2024-11-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_rename_arrival_time_train_return_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
