# Generated by Django 5.1.2 on 2024-11-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_train_amount_alter_booking_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seat',
        ),
    ]
